[tool.poetry]
name = "dango"
version = "0.0.1"
description = "Functional containers"
authors = ["Arie Bovenberg <a.c.bovenberg@gmail.com>"]
license = "MIT"
packages = [
    { include = "dango", from = "src" },
]

[tool.poetry.dependencies]
python = "^3.7"
importlib-metadata = {version = "^1.0", python = "<3.8"}

[tool.poetry.dev-dependencies]
black = "20.8b1"
flake8 = "^3.8.4"
isort = "^5.7.0"
mypy = "^0.790"
pytest = "^6.2.1"
tox = "^3.20.1"

[tool.black]
line-length = 79
include = '\.pyi?$'
exclude = '''
/(
    \.eggs
  | \.hg
  | \.git
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | build
  | dist
)/
'''

[tool.isort]
profile = 'black'
line_length = 79

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
